#!/usr/bin/env python

import sys

    input = sys.argv[1]
    res = {}
    f = open(input, 'r')
    for line in f:
        words = line.split()
        n = 1
        for i in range (1,len(words)):
            n = n * int(words[i])
        res[words[0]] = n
    print res

def min_cost(res):
    minname = ''
    mincost = sys.maxsize
    for item in res:
        if res[item] < mincost:
            mincost = res[item]
            minname=item
    return mincost

def max_cost(res):
    maxname = ''
    maxcost = -sys.maxsize
    for item in res:
        if res[item] > maxcost:
            maxcost = res[item]
            maxname = item
    return max_cost

if __name__ == '__main__':
print res
print min_cost(res)
print max_cost(res)
